### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by oaaron99** [randunel/node-srcds-rcon#16]
I get this error installing:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',  
1 verbose cli   '/usr/bin/npm',  
1 verbose cli   'install',  
1 verbose cli   'randunel/node-srcds-rcon' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'randunel/node-srcds-rcon',   null ]
5 verbose cache add name=undefined spec="randunel/node-srcds-rcon" args=["randunel/node-srcds-rcon",  null]
6 verbose parsed url { protocol: null,  
6 verbose parsed url   slashes: null,  
6 verbose parsed url   auth: null,  
6 verbose parsed url   host: null,  
6 verbose parsed url   port: null,  
6 verbose parsed url   hostname: null,  
6 verbose parsed url   hash: null,  
6 verbose parsed url   search: null,  
6 verbose parsed url   query: null,  
6 verbose parsed url   pathname: 'randunel/node-srcds-rcon',  
6 verbose parsed url   path: 'randunel/node-srcds-rcon',  
6 verbose parsed url   href: 'randunel/node-srcds-rcon' }
7 silly lockFile 662164de-randunel-node-srcds-rcon randunel/node-srcds-rcon
8 verbose lock randunel/node-srcds-rcon /root/.npm/662164de-randunel-node-srcds-rcon.lock
9 info maybeGithub Attempting randunel/node-srcds-rcon from git://github.com/randunel/node-srcds-rcon
10 silly lockFile bdb83ecc-hub-com-randunel-node-srcds-rcon git://github.com/randunel/node-srcds-rcon
11 verbose lock git://github.com/randunel/node-srcds-rcon /root/.npm/bdb83ecc-hub-com-randunel-node-srcds-rcon.lock
12 verbose addRemoteGit [ 'git://github.com/randunel/node-srcds-rcon',   'master' ]
13 silly lockFile bdb83ecc-hub-com-randunel-node-srcds-rcon git://github.com/randunel/node-srcds-rcon
14 silly lockFile bdb83ecc-hub-com-randunel-node-srcds-rcon git://github.com/randunel/node-srcds-rcon
15 info maybeGithub Attempting randunel/node-srcds-rcon from git+ssh://git@github.com:randunel/node-srcds-rcon
16 silly lockFile 58b1587a-hub-com-randunel-node-srcds-rcon git+ssh://git@github.com:randunel/node-srcds-rcon
17 verbose lock git+ssh://git@github.com:randunel/node-srcds-rcon /root/.npm/58b1587a-hub-com-randunel-node-srcds-rcon.lock
18 verbose addRemoteGit [ 'git@github.com:randunel/node-srcds-rcon',   'master' ]
19 silly lockFile cbff231c-hub-com-randunel-node-srcds-rcon git@github.com:randunel/node-srcds-rcon
20 silly lockFile 662164de-randunel-node-srcds-rcon randunel/node-srcds-rcon
21 silly lockFile 662164de-randunel-node-srcds-rcon randunel/node-srcds-rcon
22 error addLocal Could not install randunel/node-srcds-rcon
23 error Error: ENOENT,   stat 'randunel/node-srcds-rcon'
24 error If you need help,   you may report this log at:
24 error     http://github.com/isaacs/npm/issues
24 error or email it to:
24 error     npm-@googlegroups.com
25 error System Linux 3.13.0-85-generic
26 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "randunel/node-srcds-rcon"
27 error cwd /root
28 error node -v v0.10.25
29 error npm -v 1.3.10
30 error path randunel/node-srcds-rcon
31 error code ENOENT
32 error errno 34
33 verbose exit [ 34,   true ]

**Comment by randunel** [comment]
Hi. Sorry, node 0.10 is no longer supported by the latest versions.

Use the old, unsupported version 1.1.7 for 0.10:

```
npm install srcds-rcon@1.1.7
```
