### ISSUE TITLE
Is it possible to do something with rcon status and playercounters?

### ISSUE THREAD

**Issue by Bart435** [randunel/node-srcds-rcon#26]
I know this package is old, But i was wondering if it was possible with this package, Since there are not much package out there that do allows you to do such things as this package can. But to make the situation a bit clearer, In my application, I'm using it for ark rcons, But there are no commands for status or playerlists. Thank you in advance.

**Comment by randunel** [comment]
Hi! Indeed, the project isn't actively maintained, and I've only ever tested it against HL/Source games. It would help a lot if you could provide sample data (e.g. a data dump of expected request and another one with the expected response). Alternatively, could you share the expected functionality and why you think it does not work? Someone else might provide the data dumps needed to build the feature. Cheers!

**Comment by Bart435** [comment]
> Hi! Indeed, the project isn't actively maintained, and I've only ever tested it against HL/Source games. It would help a lot if you could provide sample data (e.g. a data dump of expected request and another one with the expected response). Alternatively, could you share the expected functionality and why you think it does not work? Someone else might provide the data dumps needed to build the feature. Cheers!

**Comment by Bart435** [comment]
I closed it by accident, What i wanted to say. I got a few samples how the rcon looks like for ark, I got a link to what i currently have set up now. This is command is used for rcon commands and not for status purpose. And i have made a screenshot of how the end result can look like. Sorry again for closing this by accident. i hope you can help me further with this. Thank you in advance

https://imgur.com/Bu63rZ3
https://imgur.com/3Wcrzzp
https://sourceb.in/TkTGtvbzvs

**Comment by Bart435** [comment]
The tricky part is of this is that there is no such command as "status", "Playerlist" for ark consoles.
