### ISSUE TITLE
Need a little bit of help

### ISSUE THREAD

**Issue by pmk010** [randunel/node-srcds-rcon#4]
I am currently working on a project and require the execution of commands on a remote tf2 server. 

When I try to execute commands in the same way the example suggests, I don't have any command executed. But it seems to connect, well I don't get an error.

I am not quite sure what I am doing wrong. I am sure I have the correct password.

I would appreciate any help or guidance, here is my code.

```
var Rcon = require('srcds-rcon');

var rcon = new Rcon('iphidden', 'passwordhidden');

rcon.connect(function() {
	console.log('connected');
    rcon.kick('pmk010', function(err, res) {
        console.log('kicked player pmk010', res);
    });
});
```

**Comment by randunel** [comment]
`cvarlist` removed in v2.
