### ISSUE TITLE
Working well, but...

### ISSUE THREAD

**Issue by jeremybras** [randunel/node-srcds-rcon#8]
Hi!

This package is working well, but sometimes, I try to send a rcon command to a server and it doesn't work. I try again seconds later, it still fails, and at third, or fourth attempt, it sends the command to the server.
No error caught on the cath instruction, no message returned from the command() function...

Thx for reading!

**Comment by randunel** [comment]
Hello, thanks for the bug report.

I believe you're getting stalls due to lost packets. I added handling for old commands when newer ones succeed. I also added command timeouts as a last resort solution, so your program should no longer hang.

Run

``` javascript
let timeout = 1000; // milliseconds
rcon.command('my_command', timeout)
```
