### ISSUE TITLE
Multiple packet responses

### ISSUE THREAD

**Issue by mgibeau** [randunel/node-srcds-rcon#9]
Hey, great project!

I just started using this in a personal project and I was wondering if you have any plans to support multiple-packet responses for queries like 'cvarlist', etc.

https://developer.valvesoftware.com/wiki/RCON#Multiple-packet_Responses

**Comment by randunel** [comment]
@mgibeau multiple packets are already supported. Examples use `cvarlist` to show that. Feel free to try it out!
